name: charts_flutter_core
description: Flutter chart Core.
version: 17.4.46

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utf: ^0.9.0+5
  url_launcher: ">=5.1.3 <5.5.1"

flutter: